-- Create short share links for public share pages
create table if not exists public.share_shortlinks (
  id bigint generated by default as identity primary key,
  item_id uuid not null unique,
  created_at timestamptz not null default now()
);

alter table public.share_shortlinks enable row level security;

-- Public can resolve short links
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'share_shortlinks'
      and policyname = 'Anyone can view share shortlinks'
  ) then
    create policy "Anyone can view share shortlinks"
    on public.share_shortlinks
    for select
    using (true);
  end if;
end $$;

-- Admins can manage
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'share_shortlinks'
      and policyname = 'Admins can manage share shortlinks'
  ) then
    create policy "Admins can manage share shortlinks"
    on public.share_shortlinks
    for all
    using (
      exists (
        select 1 from public.admin_users
        where admin_users.user_id = auth.uid()
          and admin_users.is_admin = true
      )
    )
    with check (
      exists (
        select 1 from public.admin_users
        where admin_users.user_id = auth.uid()
          and admin_users.is_admin = true
      )
    );
  end if;
end $$;

create index if not exists idx_share_shortlinks_item_id on public.share_shortlinks (item_id);
